export const ALL_DOCTORS_REQUEST = "ALL_DOCTORS_REQUEST";
export const ALL_DOCTORS_SUCCESS = "ALL_DOCTORS_SUCCESS";
export const ALL_DOCTORS_FAIL = "ALL_DOCTORS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"